# Use postgres/example user/password credentials
version: "1.0"

services:

  db:
    image: surrealdb/surrealdb:latest
    restart: on-failure
    command:
      - start
      - --log=trace
      - --user=root
      - --pass=root
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 8000:8000

  api:
    container_name: api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db

networks:
  db:
    driver: bridge

volumes:
  db:
